### ISSUE TITLE
Поправьте тесты, они у вас падают

### ISSUE THREAD

**Issue by coursar** [Muhammadnumon/queue#8]

**Comment by coursar** [comment]
Поправить надо было так, чтобы они работали, а не удалять неработающий кусок

**Comment by Muhammadnumon** [comment]
@coursar 

> Поправить надо было так, чтобы они работали, а не удалять неработающий кусок

Я здесь добавляю 1 элемент и проверяю на первый и последний элемент, где значение первого
и последнего должны быть одинаковы

**Comment by Muhammadnumon** [comment]
@coursar 

> Поправить надо было так, чтобы они работали, а не удалять неработающий кусок

Я здесь добавляю 1 элемент и проверяю на первый и последний элемент, где значение первого
и последнего должны быть одинаковы
